samples: config/samples.tsv
units: config/units.tsv

ref:
  genome:
        "resources/reference/aedes-aegypti-lvpagwg_chromosomes.l5.fa"
  transcriptome:
        "resources/reference/aedes-aegypti-lvpagwg_transcripts.l5.fa"
  gtf: 
        "resources/reference/Aedes-aegypti-LVP_AGWG_BASEFEATURES_AaegL5.2.gtf"
  snpeffdb:
        "Aedes_aegypti_lvpagwg"

# Chromosome names for the appropriate species. Should correspond to the reference files. 
chroms: ['1', '2', '3']

# ploidy level for freebayes, as generally we are using pooled samples.
ploidy: 10

# If activate:True, creates allele balance .xlsx reports on IR mutations of choice
IRmutations: 
      activate: True
      path: "resources/IRmutations.tsv"

