# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 
author: Sanjay Curtis Nagi
copyright: "2023"
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"

# Information about where the book exists on the web
repository:
  url: https://github.com/sanjaynagi/rna-seq-pop  # Online location of your book
  path_to_book: docs/rna-seq-pop-results  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  comments:
    utterances:
      repo: "sanjaynagi/rna-seq-pop"
      issue-term: "pathname"
      label: "comment"
      theme: "github-light" 


sphinx:
    extra_extensions:
        - 'sphinx.ext.autodoc'
        - 'sphinx.ext.napoleon'
    config:
        myst_enable_extensions:
            - substitution
            - dollarmath
        html_js_files:
            - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
        suppress_warnings: ["mystnb.unknown_mime_type"]